image: node:14-buster

cache:
    paths:
        - node_modules/

stages:
    - prepare
    - test

yarn-install:
    stage: prepare
    script:
        - yarn install

test:
    stage: test
    script:
        - yarn test --ci=true

eslint:
    stage: test
    script:
        - yarn eslint .